#!/usr/bin/env python
import difflib
from optparse import OptionParser
import os

parser = OptionParser()
parser.add_option( '-f', '--files', type='str', action='append', dest='filenames' )
( options, args ) = parser.parse_args()

file1 = open( options.filenames[0] )
file2 = open( options.filenames[1] )

a = file1.readlines()
file1.close()
b = file2.readlines()
file2.close()

deletions = open('deletions.csv', 'w')
additions = open('additions.csv', 'w')
matches = open('matches.csv', 'w')

deletions.write( a[0] )
additions.write( a[0] )

for line in a:
    if line not in b:
        deletions.write( line )
    else:
        matches.write( line )
for line in b:
    if line not in a:
        additions.write( line )

deletions.close()
additions.close()
matches.close()
