#!/usr/bin/env python

from argparse import ArgumentParser
import random

parser = OptionParser()
parser.add_argument('-f', '--filename', type='str', action='store', dest='filename')
parser.add_argument('-o', '--output', type='str', action='store', dest='output', default='output.csv')
parser.add_argument('-s', '--sample', type='int', action='store', dest='sample', default=250)
options = parser.parse_args()

lineOffset = []
offset = 0
file = open(options.filename,'r')
header = file.readline()
outFile = open(options.output,'w')
outFile.write(header)
file.close()
file = open(options.filename,'r')

for line in file:
    lineOffset.append(offset)
    offset += len(line)

file.seek(0)

randomOffsets = random.sample(lineOffset[1:], options.sample)

for rand in randomOffsets:
    file.seek(rand)
    outFile.write(file.readline())
    
file.close()
outFile.flush()
outFile.close()
